name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install German locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8
          export LANG=de_DE.UTF-8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python test_generate_weekly_report.py

      - name: Upload generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: test_weekly_report_*.pdf
