name: Test Mail Versand

on:
  workflow_dispatch:  # Manuell startbar

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install reportlab

      - name: Create dummy PDF
        run: python test_mail.py

      - name: Send test PDF via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "BFH Bot – Testmail"
          to: ulrich.wilke@wieselukas.de   # 👉 Empfänger anpassen
          from: ${{ secrets.EMAIL_USER }}
          body: |
            Guten Tag,

            dies ist eine Testmail vom GitHub Workflow.
            Wenn Sie die angehängte Test-PDF sehen, funktioniert der Versand.

            Viele Grüße
            Ihr BFH-Bot
          attachments: weekly_reports/Dummy_Test.pdf
